# Site settings
title: ${_("A Practical Guide to Sociocracy 3.0")}
email: bernhard.bockelbrink@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   ${_("The official description of Sociocracy 3.0 - All patterns, the Seven Principles and key concepts. Maintained by Bernhard Bockelbrink, James Priest and Liliana David.")}

baseurl: "" # subpath of the site, e.g. /blog, empty otherwise
url: "${site_url}" # the base hostname & protocol for your site
keywords: "sociocracy, holacracy, s3, scrum, kanban, agile, lean"
author: "Bernhard Bockelbrink, James Priest, Liliana David"
githuburl: "https://github.com/bboc/mdtools"

twitter_username: sociocracy30

# Build settings
source:   .
destination:  ./_site
layouts_dir:  ./_layouts
includes_dir: ./_includes


markdown: kramdown
safe: true # required on Github pages (no plugins)

kramdown:
  toc_levels: 2..4

# plugins:
#   - jekyll-redirect-from

# whitelist:
#   - jekyll-redirect-from

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page" # overrides previous default layout


exclude:      [
  "_export",
  "_python",
  "_templates",
  ]
